apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: runtime-timeout-template
objects:
- kind: KubeletConfig
  apiVersion: machineconfiguration.openshift.io/v1
  metadata: 
    generateName: "${NAME}"
  spec:
    machineConfigPoolSelector:
      matchLabels:
        "${LABELKEY}": "${LABELVALUE}"
      #aro.openshift.io/limits: ""
    kubeletConfig:
      runtimeRequestTimeout: 3m
parameters:
- name: NAME
- name: LABELKEY
- name: LABELVALUE
